Домашнее задание по уроку 1

In [1]:
import torch

In [ ]:
# 1. Создайте случайный FloatTensor размера 3x4x5

In [53]:
a = torch.randn(3,4,5)
a

tensor([[[ 1.4083,  1.0368,  1.7488,  0.6104, -1.5810],
         [ 0.0590, -0.8839,  0.7831,  1.0454, -0.5579],
         [ 0.4321, -1.2704,  0.8767, -0.5392, -0.6684],
         [-0.6725, -0.1307, -0.4199,  1.5848, -1.7052]],

        [[-0.2019,  0.0506,  1.6520,  2.7273, -0.3794],
         [-0.8676, -0.1891,  1.1632, -0.1245,  0.0255],
         [ 0.2952,  0.5072,  0.3434, -0.4507,  0.5958],
         [-0.3835,  1.1861,  0.0816, -0.7182, -2.5749]],

        [[-0.0476,  2.0859,  0.2674,  0.9555,  0.2654],
         [ 1.3746, -0.2507, -1.1018,  0.0541, -1.0422],
         [-0.2511,  0.6679,  0.9108, -0.9127,  1.4361],
         [ 0.5434,  0.9317,  0.0219, -0.7407, -1.2913]]])

In [46]:
a.type()

'torch.FloatTensor'

In [ ]:
# 2. Выведите его форму (shape)

In [47]:
a.shape

torch.Size([3, 4, 5])

In [ ]:
# 3. Приведите его к форме 6х10

In [54]:
a = a.reshape(6, 10)

In [55]:
a

tensor([[ 1.4083,  1.0368,  1.7488,  0.6104, -1.5810,  0.0590, -0.8839,  0.7831,
          1.0454, -0.5579],
        [ 0.4321, -1.2704,  0.8767, -0.5392, -0.6684, -0.6725, -0.1307, -0.4199,
          1.5848, -1.7052],
        [-0.2019,  0.0506,  1.6520,  2.7273, -0.3794, -0.8676, -0.1891,  1.1632,
         -0.1245,  0.0255],
        [ 0.2952,  0.5072,  0.3434, -0.4507,  0.5958, -0.3835,  1.1861,  0.0816,
         -0.7182, -2.5749],
        [-0.0476,  2.0859,  0.2674,  0.9555,  0.2654,  1.3746, -0.2507, -1.1018,
          0.0541, -1.0422],
        [-0.2511,  0.6679,  0.9108, -0.9127,  1.4361,  0.5434,  0.9317,  0.0219,
         -0.7407, -1.2913]])

In [ ]:
# 4. Создайте случайный IntTensor размера 10

In [82]:
b = torch.randint(100, size=(10,))
b

tensor([80, 88, 19, 36, 99, 27,  0, 62, 61, 74])

In [ ]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [85]:
c = torch.mul(a, b)
c

tensor([[ 112.6618,   91.2358,   33.2280,   21.9729, -156.5238,    1.5926,
           -0.0000,   48.5511,   63.7718,  -41.2836],
        [  34.5672, -111.7989,   16.6574,  -19.4106,  -66.1680,  -18.1578,
           -0.0000,  -26.0367,   96.6723, -126.1875],
        [ -16.1490,    4.4555,   31.3886,   98.1839,  -37.5600,  -23.4259,
           -0.0000,   72.1198,   -7.5956,    1.8844],
        [  23.6148,   44.6327,    6.5237,  -16.2242,   58.9834,  -10.3554,
            0.0000,    5.0568,  -43.8088, -190.5394],
        [  -3.8116,  183.5583,    5.0809,   34.3989,   26.2787,   37.1147,
           -0.0000,  -68.3119,    3.2989,  -77.1214],
        [ -20.0919,   58.7744,   17.3051,  -32.8564,  142.1741,   14.6726,
            0.0000,    1.3609,  -45.1856,  -95.5585]])

In [ ]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [ ]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

3y, 0.75y, 12y

In [ ]:
# 8. Создайте единичный тензор размера 5x6

In [43]:
v = torch.ones(5,6)
v

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
# 9. Переведите его в формат numpy

In [40]:
v.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)